version: '3'
services:
  db:
    container_name: postgres-container
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      POSTGRES_USER: maximan
      POSTGRES_PASSWORD: Makong57
      PGDATA: /data/postgres
      POSTGRES_DB: sandagadb
      POSTGRES_EXTENSIONS: postgis, uuid-ossp
    ports:
      - "5432:5432"
    volumes:
      #- db-data:/data/postgres
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - db
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-h", "localhost", "-U", "maximan", "-d", "sandagadb" ]
      interval: 5s
      timeout: 1s
      retries: 2
  sandaga-api:
    container_name: sandaga-api
    image: cartman81/sandaga-api
    environment:
      SPRING_DATASOURCE: jdbc:postgresql://db:5432/sandagadb
    ports:
      - "8088:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped

  sandaga-frontend:
    container_name: sandaga-frontend
    image: cartman81/sandaga-frontend
    build:
      context: sandaga-frontend
    ports:
      - "3000:3000"
    networks:
      - db
    depends_on:
      - sandaga-api
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "9090:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - db

networks:
  db:
    driver: bridge
volumes:
  db-data:
  pgadmin-data:
  sandaga-api-data:

#  flyway:
#    image: boxfuse/flyway:5-alpine
#    command: -url=jdbc:postgresql://db:5432/sandagadb -schemas=public -user=maximan  -password=Makong57 -connectRetries=60 migrate -X
#    volumes:
#      - ./migration:/flyway/sql
#    depends_on:
#      db:
#        condition: service_healthy

