pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/lead-tech-dev/sandaga-backend.git',
                branch: 'main',
                credentialsId: 'git-credentials'
            }
        }
    }
}