package com.mjtech.sandaga.utility.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.mjtech.sandaga.dtos.criteria.CriteriaDto;
import com.mjtech.sandaga.dtos.search.CriteriaReq;
import com.mjtech.sandaga.entity.CriteriaEntity;

import java.util.Collections;
import java.util.List;
import java.util.Objects;
import java.util.UUID;
import java.util.stream.Collectors;

public class Criteria {

    public static CriteriaDto toDto(CriteriaEntity entity) {

        return CriteriaDto.builder()
                .item_condition(entity.getItem_condition())
                .video_game_type(entity.getVideo_game_type())
                .console_model(entity.getConsole_model())
                .image_sound_product(entity.getImage_sound_product())
                .image_sound_type_of_product(entity.getImage_sound_type_of_product())
                .phone_brand(entity.getPhone_brand())
                .phone_model(entity.getPhone_model())
                .phone_color(entity.getPhone_color())
                .phone_memory(entity.getPhone_memory())
                .furniture_color(entity.getFurniture_color())
                .furniture_type(entity.getFurniture_type())
                .furniture_material(entity.getFurniture_material())
                .home_appliance_type(entity.getHome_appliance_type())
                .home_appliance_product(entity.getHome_appliance_product())
                .home_appliance_brand(entity.getHome_appliance_brand())
                .table_art_material(entity.getTable_art_material())
                .table_art_product(entity.getTable_art_product())
                .decoration_type(entity.getDecoration_type())
                .linens_type(entity.getLinens_type())
                .linens_product(entity.getLinens_product())
                .linens_material(entity.getLinens_material())
                .diy_type(entity.getDiy_type())
                .diy_product(entity.getDiy_product())
                .gardening_product(entity.getGardening_product())
                .gardening_type(entity.getGardening_type())
                .clothing_type(entity.getClothing_type())
                .clothing_st(entity.getClothing_st())
                .clothing_brand(entity.getClothing_brand())
                .clothing_category(entity.getClothing_category())
                .clothing_category(entity.getClothing_color())
                .clothing_condition(entity.getClothing_condition())
                .shoe_type(entity.getShoe_type())
                .shoe_category(entity.getShoe_category())
                .shoe_size(entity.getShoe_size())
                .shoe_brand(entity.getShoe_brand())
                .accessories_univers(entity.getAccessories_univers())
                .accessories_type(entity.getAccessories_type())
                .accessories_brand(entity.getAccessories_brand())
                .accessories_material(entity.getAccessories_material())
                .watches_jewels_type(entity.getWatches_jewels_type())
                .watches_jewels_brand(entity.getWatches_jewels_brand())
                .watches_jewels_material(entity.getWatches_jewels_material())
                .baby_equipment_type(entity.getBaby_equipment_type())
                .baby_equipment_brand(entity.getBaby_equipment_brand())
                .baby_clothing_brand(entity.getBaby_clothing_brand())
                .baby_clothing_category(entity.getBaby_clothing_category())
                .baby_age(entity.getBaby_age())
                .bicycle_type(entity.getBicycle_type())
                .bicycle_size(entity.getBicycle_size())
                .bicycode(entity.getBicycode())
                .sports_hobbies_activity(entity.getSports_hobbies_activity())
                .toy_age(entity.getToy_age())
                .toy_type(entity.getToy_type())
                .matpro_agriculture_equipment_type(entity.getMatpro_agriculture_equipment_type())
                .matpro_transport_handling_equipment_type(entity.getMatpro_transport_handling_equipment_type())
                .matpro_btp_equipment_type(entity.getMatpro_btp_equipment_type())
                .regdate(entity.getRegdate())
                .build();
    }
    public static CriteriaDto criteriaReqToDto(CriteriaReq criteriaReq) {

        return CriteriaDto.builder()
                .item_condition(criteriaReq.getItem_condition())
                .video_game_type(criteriaReq.getVideo_game_type())
                .console_model(criteriaReq.getConsole_model())
                .image_sound_product(criteriaReq.getImage_sound_product())
                .image_sound_type_of_product(criteriaReq.getImage_sound_type_of_product())
                .phone_brand(criteriaReq.getPhone_brand())
                .phone_model(criteriaReq.getPhone_model())
                .phone_color(criteriaReq.getPhone_color())
                .phone_memory(criteriaReq.getPhone_memory())
                .furniture_color(criteriaReq.getFurniture_color())
                .furniture_type(criteriaReq.getFurniture_type())
                .furniture_material(criteriaReq.getFurniture_material())
                .home_appliance_type(criteriaReq.getHome_appliance_type())
                .home_appliance_product(criteriaReq.getHome_appliance_product())
                .home_appliance_brand(criteriaReq.getHome_appliance_brand())
                .table_art_material(criteriaReq.getTable_art_material())
                .table_art_product(criteriaReq.getTable_art_product())
                .decoration_type(criteriaReq.getDecoration_type())
                .linens_type(criteriaReq.getLinens_type())
                .linens_product(criteriaReq.getLinens_product())
                .linens_material(criteriaReq.getLinens_material())
                .diy_type(criteriaReq.getDiy_type())
                .diy_product(criteriaReq.getDiy_product())
                .gardening_product(criteriaReq.getGardening_product())
                .gardening_type(criteriaReq.getGardening_type())
                .clothing_type(criteriaReq.getClothing_type())
                .clothing_st(criteriaReq.getClothing_st())
                .clothing_brand(criteriaReq.getClothing_brand())
                .clothing_category(criteriaReq.getClothing_category())
                .clothing_category(criteriaReq.getClothing_color())
                .clothing_condition(criteriaReq.getClothing_condition())
                .shoe_type(criteriaReq.getShoe_type())
                .shoe_category(criteriaReq.getShoe_category())
                .shoe_size(criteriaReq.getShoe_size())
                .shoe_brand(criteriaReq.getShoe_brand())
                .accessories_univers(criteriaReq.getAccessories_univers())
                .accessories_type(criteriaReq.getAccessories_type())
                .accessories_brand(criteriaReq.getAccessories_brand())
                .accessories_material(criteriaReq.getAccessories_material())
                .watches_jewels_type(criteriaReq.getWatches_jewels_type())
                .watches_jewels_brand(criteriaReq.getWatches_jewels_brand())
                .watches_jewels_material(criteriaReq.getWatches_jewels_material())
                .baby_equipment_type(criteriaReq.getBaby_equipment_type())
                .baby_equipment_brand(criteriaReq.getBaby_equipment_brand())
                .baby_clothing_brand(criteriaReq.getBaby_clothing_brand())
                .baby_clothing_category(criteriaReq.getBaby_clothing_category())
                .baby_age(criteriaReq.getBaby_age())
                .bicycle_type(criteriaReq.getBicycle_type())
                .bicycle_size(criteriaReq.getBicycle_size())
                .bicycode(criteriaReq.getBicycode())
                .sports_hobbies_activity(criteriaReq.getSports_hobbies_activity())
                .toy_age(criteriaReq.getToy_age())
                .toy_type(criteriaReq.getToy_type())
                .matpro_agriculture_equipment_type(criteriaReq.getMatpro_agriculture_equipment_type())
                .matpro_transport_handling_equipment_type(criteriaReq.getMatpro_transport_handling_equipment_type())
                .matpro_btp_equipment_type(criteriaReq.getMatpro_btp_equipment_type())
                .regdate(criteriaReq.getRegdate())
                .build();
    }

    public static CriteriaReq entityTocriteriaReq(CriteriaEntity entity) {

        return CriteriaReq.builder()
                .ad_type("sell")
                .item_condition(entity.getItem_condition())
                .video_game_type(entity.getVideo_game_type())
                .console_model(entity.getConsole_model())
                .image_sound_product(entity.getImage_sound_product())
                .image_sound_type_of_product(entity.getImage_sound_type_of_product())
                .phone_brand(entity.getPhone_brand())
                .phone_model(entity.getPhone_model())
                .phone_color(entity.getPhone_color())
                .phone_memory(entity.getPhone_memory())
                .furniture_color(entity.getFurniture_color())
                .furniture_type(entity.getFurniture_type())
                .furniture_material(entity.getFurniture_material())
                .home_appliance_type(entity.getHome_appliance_type())
                .home_appliance_product(entity.getHome_appliance_product())
                .home_appliance_brand(entity.getHome_appliance_brand())
                .table_art_material(entity.getTable_art_material())
                .table_art_product(entity.getTable_art_product())
                .decoration_type(entity.getDecoration_type())
                .linens_type(entity.getLinens_type())
                .linens_product(entity.getLinens_product())
                .linens_material(entity.getLinens_material())
                .diy_type(entity.getDiy_type())
                .diy_product(entity.getDiy_product())
                .gardening_product(entity.getGardening_product())
                .gardening_type(entity.getGardening_type())
                .clothing_type(entity.getClothing_type())
                .clothing_st(entity.getClothing_st())
                .clothing_brand(entity.getClothing_brand())
                .clothing_category(entity.getClothing_category())
                .clothing_category(entity.getClothing_color())
                .clothing_condition(entity.getClothing_condition())
                .shoe_type(entity.getShoe_type())
                .shoe_category(entity.getShoe_category())
                .shoe_size(entity.getShoe_size())
                .shoe_brand(entity.getShoe_brand())
                .accessories_univers(entity.getAccessories_univers())
                .accessories_type(entity.getAccessories_type())
                .accessories_brand(entity.getAccessories_brand())
                .accessories_material(entity.getAccessories_material())
                .watches_jewels_type(entity.getWatches_jewels_type())
                .watches_jewels_brand(entity.getWatches_jewels_brand())
                .watches_jewels_material(entity.getWatches_jewels_material())
                .baby_equipment_type(entity.getBaby_equipment_type())
                .baby_equipment_brand(entity.getBaby_equipment_brand())
                .baby_clothing_brand(entity.getBaby_clothing_brand())
                .baby_clothing_category(entity.getBaby_clothing_category())
                .baby_age(entity.getBaby_age())
                .bicycle_type(entity.getBicycle_type())
                .bicycle_size(entity.getBicycle_size())
                .bicycode(entity.getBicycode())
                .sports_hobbies_activity(entity.getSports_hobbies_activity())
                .toy_age(entity.getToy_age())
                .toy_type(entity.getToy_type())
                .matpro_agriculture_equipment_type(entity.getMatpro_agriculture_equipment_type())
                .matpro_transport_handling_equipment_type(entity.getMatpro_transport_handling_equipment_type())
                .matpro_btp_equipment_type(entity.getMatpro_btp_equipment_type())
                .regdate(entity.getRegdate())
                .build();
    }

    public static List<CriteriaDto> toDtoList(List<CriteriaEntity> ads) {
        if (Objects.isNull(ads)) {
            return Collections.emptyList();
        }
        return ads.stream().map(e -> toDto(e)).collect(Collectors.toList());
    }


    public static CriteriaEntity toEntity(CriteriaDto entity) {
        return CriteriaEntity.builder()
                .item_condition(entity.getItem_condition())
                .video_game_type(entity.getVideo_game_type())
                .console_model(entity.getConsole_model())
                .image_sound_product(entity.getImage_sound_product())
                .image_sound_type_of_product(entity.getImage_sound_type_of_product())
                .phone_brand(entity.getPhone_brand())
                .phone_model(entity.getPhone_model())
                .phone_color(entity.getPhone_color())
                .phone_memory(entity.getPhone_memory())
                .furniture_color(entity.getFurniture_color())
                .furniture_type(entity.getFurniture_type())
                .furniture_material(entity.getFurniture_material())
                .home_appliance_type(entity.getHome_appliance_type())
                .home_appliance_product(entity.getHome_appliance_product())
                .home_appliance_brand(entity.getHome_appliance_brand())
                .table_art_material(entity.getTable_art_material())
                .table_art_product(entity.getTable_art_product())
                .decoration_type(entity.getDecoration_type())
                .linens_type(entity.getLinens_type())
                .linens_product(entity.getLinens_product())
                .linens_material(entity.getLinens_material())
                .diy_type(entity.getDiy_type())
                .diy_product(entity.getDiy_product())
                .gardening_product(entity.getGardening_product())
                .gardening_type(entity.getGardening_type())
                .clothing_type(entity.getClothing_type())
                .clothing_st(entity.getClothing_st())
                .clothing_brand(entity.getClothing_brand())
                .clothing_category(entity.getClothing_category())
                .clothing_category(entity.getClothing_color())
                .clothing_condition(entity.getClothing_condition())
                .shoe_type(entity.getShoe_type())
                .shoe_category(entity.getShoe_category())
                .shoe_size(entity.getShoe_size())
                .shoe_brand(entity.getShoe_brand())
                .accessories_univers(entity.getAccessories_univers())
                .accessories_type(entity.getAccessories_type())
                .accessories_brand(entity.getAccessories_brand())
                .accessories_material(entity.getAccessories_material())
                .watches_jewels_type(entity.getWatches_jewels_type())
                .watches_jewels_brand(entity.getWatches_jewels_brand())
                .watches_jewels_material(entity.getWatches_jewels_material())
                .baby_equipment_type(entity.getBaby_equipment_type())
                .baby_equipment_brand(entity.getBaby_equipment_brand())
                .baby_clothing_brand(entity.getBaby_clothing_brand())
                .baby_clothing_category(entity.getBaby_clothing_category())
                .baby_age(entity.getBaby_age())
                .bicycle_type(entity.getBicycle_type())
                .bicycle_size(entity.getBicycle_size())
                .bicycode(entity.getBicycode())
                .sports_hobbies_activity(entity.getSports_hobbies_activity())
                .toy_age(entity.getToy_age())
                .toy_type(entity.getToy_type())
                .matpro_agriculture_equipment_type(entity.getMatpro_agriculture_equipment_type())
                .matpro_transport_handling_equipment_type(entity.getMatpro_transport_handling_equipment_type())
                .matpro_btp_equipment_type(entity.getMatpro_btp_equipment_type())
                .regdate(entity.getRegdate())
                .build();
    }

    public static CriteriaEntity toUpdtateEntity(CriteriaDto entity) {
        return CriteriaEntity.builder()
                .id(UUID.fromString(entity.getId()))
                .item_condition(entity.getItem_condition())
                .video_game_type(entity.getVideo_game_type())
                .console_model(entity.getConsole_model())
                .image_sound_product(entity.getImage_sound_product())
                .image_sound_type_of_product(entity.getImage_sound_type_of_product())
                .phone_brand(entity.getPhone_brand())
                .phone_model(entity.getPhone_model())
                .phone_color(entity.getPhone_color())
                .phone_memory(entity.getPhone_memory())
                .furniture_color(entity.getFurniture_color())
                .furniture_type(entity.getFurniture_type())
                .furniture_material(entity.getFurniture_material())
                .home_appliance_type(entity.getHome_appliance_type())
                .home_appliance_product(entity.getHome_appliance_product())
                .home_appliance_brand(entity.getHome_appliance_brand())
                .table_art_material(entity.getTable_art_material())
                .table_art_product(entity.getTable_art_product())
                .decoration_type(entity.getDecoration_type())
                .linens_type(entity.getLinens_type())
                .linens_product(entity.getLinens_product())
                .linens_material(entity.getLinens_material())
                .diy_type(entity.getDiy_type())
                .diy_product(entity.getDiy_product())
                .gardening_product(entity.getGardening_product())
                .gardening_type(entity.getGardening_type())
                .clothing_type(entity.getClothing_type())
                .clothing_st(entity.getClothing_st())
                .clothing_brand(entity.getClothing_brand())
                .clothing_category(entity.getClothing_category())
                .clothing_category(entity.getClothing_color())
                .clothing_condition(entity.getClothing_condition())
                .shoe_type(entity.getShoe_type())
                .shoe_category(entity.getShoe_category())
                .shoe_size(entity.getShoe_size())
                .shoe_brand(entity.getShoe_brand())
                .accessories_univers(entity.getAccessories_univers())
                .accessories_type(entity.getAccessories_type())
                .accessories_brand(entity.getAccessories_brand())
                .accessories_material(entity.getAccessories_material())
                .watches_jewels_type(entity.getWatches_jewels_type())
                .watches_jewels_brand(entity.getWatches_jewels_brand())
                .watches_jewels_material(entity.getWatches_jewels_material())
                .baby_equipment_type(entity.getBaby_equipment_type())
                .baby_equipment_brand(entity.getBaby_equipment_brand())
                .baby_clothing_brand(entity.getBaby_clothing_brand())
                .baby_clothing_category(entity.getBaby_clothing_category())
                .baby_age(entity.getBaby_age())
                .bicycle_type(entity.getBicycle_type())
                .bicycle_size(entity.getBicycle_size())
                .bicycode(entity.getBicycode())
                .sports_hobbies_activity(entity.getSports_hobbies_activity())
                .toy_age(entity.getToy_age())
                .toy_type(entity.getToy_type())
                .matpro_agriculture_equipment_type(entity.getMatpro_agriculture_equipment_type())
                .matpro_transport_handling_equipment_type(entity.getMatpro_transport_handling_equipment_type())
                .matpro_btp_equipment_type(entity.getMatpro_btp_equipment_type())
                .regdate(entity.getRegdate())
                .build();
    }
}
