

export const GlobalsActionTypes = {
   RESET: 'RESET',
   LOADING: 'LOADING',
   FOLLOW_LOADING: "FOLLOW_LOADING",
   SUCCESS: "SUCCESS",
   CLEAR_ERRORS: "CLEAR_ERRORS",
   UPDATE_LOADING: "UPDATE_LOADING",
   UPDATING_PROCESS: "UPDATING_PROCESS",
   CLEAR_UPDATING_PROCESS: "CLEAR_UPDATING_PROCESS",
    UPDATE_SUCCESS: "UPDATE_SUCCESS",
    UPDATE_EMAIL_LOADING: "UPDATE_EMAIL_LOADING",
    UPDATE_EMAIL_SUCCESS: "UPDATE_EMAIL_SUCCESS",
    UPDATE_EMAIL_FAILURE: "UPDATE_EMAIL_FAILURE",

    UPDATE_INFO_LOADING: "UPDATE_INFO_LOADING",
    UPDATE_INFO_SUCCESS: "UPDATE_INFO_SUCCESS",
    UPDATE_INFO_FAILURE: "UPDATE_INFO_FAILURE",

    UPDATE_ADDRESS_SUCCESS: "UPDATE_ADDRESS_SUCCESS",
    UPDATE_ADDRESS_LOADING: "UPDATE_ADDRESS_LOADING",
    UPDATE_ADDRESS_FAILURE: "UPDATE_ADDRESS_FAILURE",

    USER_DELETE__SUCCESS: "USER_DELETE__SUCCESS",
    USER_DELETE__LOADING: "USER_DELETE__LOADING",
    USER_DELETE_FAILURE: "USER_DELETE_FAILURE"

} as const;