export const SearchActionTypes = {
  ADD_LOCATION: "ADD_LOCATION",
  REMOVE_LOCATION: "REMOVE_LOCATION",
  CLEAR_LOCATION: "CLEAR_LOCATION",
  LOADING: "LOADING",
  ADD_CATEGORY: "ADD_CATEGORY",
  ADD_RECENT_SEARCH: "ADD_RECENT_SEARCH",
  DELETE_FILTERS: "DELETE_FILTERS",
  SEARCH_REQUEST: "SEARCH_REQUEST",
  SEARCH_SUCCESS: "SEARCH_SUCCESS",
  SEARCH_ERROR: "SEARCH_ERROR"

} as const;

