name: CI-Build Backend
on:
  pull_request:
    branches:
      - main
    paths:
      - sandaga-backend/**
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15.5
        env:
          POSTGRES_USER: maximan
          POSTGRES_PASSWORD: Makong57
          POSTGRES_DB: sandagadb

        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    defaults:
      run:
        working-directory: ./sandaga-backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
         distribution: 'temurin'
         java-version: '11'
         cache: 'gradle'
      - name: Build and run unit/integration Tests with gradle
        run: ./gradlew build