on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - sandaga-backend/**
jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:15-3.4
        env:
          POSTGRES_USER: maximan
          POSTGRES_PASSWORD: Makong57
          POSTGRES_DB: sandagadb

        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
#    defaults:
#      run:
#        working-directory: ./sandaga-backend
    steps:
      - name: Send Slack Message
        run: >
          curl --data-urlencode "payload={\"channel\": \"#sandaga-api-app\", \"username\": \"maximancode\", \"text\": \"Deployment stated.\", \"icon_emoji\": \":progress_bar: :fingerscrossed:\"}" 
          -X POST https://hooks.slack.com/services/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
