on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - sandaga-backend/**
jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:15-3.4
        env:
          POSTGRES_USER: maximan
          POSTGRES_PASSWORD: Makong57
          POSTGRES_DB: sandagadb

        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
#    defaults:
#      run:
#        working-directory: ./sandaga-backend
    steps:
      - name: Send Slack Message
        run: >
         curl -H 'Content-type: application/json'
         -d '{"text":"Deployment stated :progress_bar: :fingerscrossed:"}'
         -X POST ${{ secrets.SLACK_WEBHOOK_URL }}
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
         username: ${{secrets.DOCKERHUB_USERNAME}}
         password: ${{secrets.DOCKERHUB_ACCESS_TOKEN}}
      - name: Set build number
        id: build_number
        run: echo "BUILD_NUMBER=$(date '+%d.%m.%Y.%H.%M.%S')" >> $GITHUB_OUTPUT
      - name: Send Slack Message
        run: >
          curl  -H 'Content-type: application/json'
          -d '{"text":"Building with gradle :gradle:"}' 
          -X POST ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Build package push with gradle
        working-directory: ./sandaga-backend
        run: ./gradlew build -Dargs=${{steps.build_number.outputs.BUILD_NUMBER}} jib
      - name: Send Slack Message
        run: >
          curl -H 'Content-type: application/json'
          -d '{"text":":docker: Image tag:${{steps.build_number.outputs.BUILD_NUMBER}} pushed to https://hub.docker.com/repository/docker/cartman81/sandaga-api"}' 
          -X POST ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Update Dockerrun.aws.json api image tag with new build number
        working-directory: ./sandaga-backend
        run: |
          echo "Dockerrun.aws.json before updating tag"
          cat ../Dockerrun.aws.json
          sed -i -E 's_(cartman81/sandaga-api:)([^"]*)_\1'${{steps.build_number.outputs.BUILD_NUMBER}}'_' ../Dockerrun.aws.json
          echo "Dockerrun.aws.json after updating tag"
          cat ../Dockerrun.aws.json
      - name: Send Slack Message
        run: >
          curl -H 'Content-type: application/json'
          -d '{"text":":aws: Starting deployment to Elastic Beanstalk :gradle:"}' 
          -X POST ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
         aws_access_key: ${{secrets.AWS_ACCESS_KEY_ID}}
         aws_secret_key:  ${{secrets.AWS_SECRET_ACCESS_KEY}}
         application_name:  ${{secrets.EB_APPLICATION_NAME}}
         environment_name:  ${{secrets.EB_ENVIRONMENT_NAME}}
         version_label:  ${{steps.build_number.outputs.BUILD_NUMBER}}
         version_description:  ${{github.SHA}}
         region:  ${{secrets.EB_REGION}}
         deployment_package: Dockerrun.aws.json
      - name: Send Slack Message
        run: >
          curl -H 'Content-type: application/json'
          -d '{"text":":githubloading: Committing to repo https://github.com/lead-tech-dev/sandaga-project"}' 
          -X POST ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Commit and push Dockerrun.aws.json
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ../Dockerrun.aws.json
          git commit -m "update Dockerrun.aws.json image with new tag ${{steps.build_number.outputs.BUILD_NUMBER}}"
          git push
      - name: Send Slack Message
        run: >
          curl -H 'Content-type: application/json'
          -d '{"text":"Deployment and Commit completed :github_check_mark: :party_blob: - http://sandaga-api-env.eba-9qih3c3p.eu-west-3.elasticbeanstalk.com"}' 
          -X POST ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Send Slack Message
        if: always()
        run: >
          curl -H 'Content-type: application/json'
          -d '{"text":"Job Status ${{ job.status }}"}' 
          -X POST ${{ secrets.SLACK_WEBHOOK_URL }}