on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - sandaga-backend/**
jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:15-3.4
        env:
          POSTGRES_USER: maximan
          POSTGRES_PASSWORD: Makong57
          POSTGRES_DB: sandagadb

        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Send Slack Message
        run: >
          curl -d '{"text":"Deployment stated :progress_bar: :fingerscrossed:"}'  
          -H 'Content-type: application/json'
          -X POST ${{ secrets.SLACK_WEBHOOK_URL }}
