on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - sandaga-frontend/**
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sandaga-frontend
    steps:
      - uses: actions/checkout@v4
      - name: Slack commit message and SHA
        run: >
          curl -H 'Content-type: application/json'
          -d '{"text":":github: ${{github.server_url}}/${{github.repository}}/commit/${{github.sha}}"}'
          -X POST ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Send slack message
        run: >
          curl -H 'Content-type: application/json'
          -d '{"text":"Deployment stated :progress_bar: :fingerscrossed:"}'
          -X POST ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Set build number
        id: build-number
        run: echo "BUILD_NUMBER=$(date '+%d.%m.%Y.%H.%M.%S')" >> $GITHUB_OUTPUT
      - name: Login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Docker build and push
        run: |
          chmod +x ../.ci/build-publish.sh
          USERNAME = cartman81 \
          REPO = sandaga-frontend \
          TAG = ${{steps.build-number.outputs.BUILD_NUMBER}} \
          ../.ci/build-publish.sh . \
          --build-arg api_base_url=http://sandaga-api-env-2.eba-9qih3c3p.eu-west-3.elasticbeanstalk.com:8080
      - name: Send slack message
        run: >
          curl -H 'Content-type: application/json'
          -d '{"text":":docker: Image tag:${{steps.build_number.outputs.BUILD_NUMBER}} pushed to https://hub.docker.com/repository/docker/cartman81/sandaga-frontend"}' 
          -X POST ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Update Dockerrun.aws.json react image tag with new build number
        run: |
          echo "Dockerrun.aws.json before updating tag"
          cat ../Dockerrun.aws.json
          sed -i -E 's_(cartman81/sandaga-api:)([^"]*)_\1'${{steps.build_number.outputs.BUILD_NUMBER}}'_' ../Dockerrun.aws.json
          echo "Dockerrun.aws.json after updating tag"
          cat ../Dockerrun.aws.json
      - name: Send slack message
        run: >
          curl -H 'Content-type: application/json'
          -d '{"text":":aws: Starting deployment to Elastic Beanstalk :gradle:"}' 
          -X POST ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          application_name: ${{secrets.EB_APPLICATION_NAME}}
          environment_name: ${{secrets.EB_ENVIRONMENT_NAME}}
          version_label: ${{steps.build_number.outputs.BUILD_NUMBER}}
          version_description: ${{github.SHA}}
          region: ${{secrets.EB_REGION}}
          deployment_package: Dockerrun.aws.json
          wait_for_environment_recovery: 60
      - name: Send Slack Message
        run: >
          curl -H 'Content-type: application/json'
          -d '{"text":":githubloading: Committing to repo https://github.com/lead-tech-dev/sandaga-project"}' 
          -X POST ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Commit and push Dockerrun.aws.json
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ../../Dockerrun.aws.json
          git commit -m "update Dockerrun.aws.json image with new tag ${{steps.build_number.outputs.BUILD_NUMBER}}"
          git push
      - name: Send Slack Message
        run: >
          curl -H 'Content-type: application/json'
          -d '{"text":"Deployment and Commit completed :github_check_mark: :party_blob: - http://sandaga-api-env.eba-9qih3c3p.eu-west-3.elasticbeanstalk.com"}' 
          -X POST ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Send Slack Message
        if: always()
        run: >
          curl -H 'Content-type: application/json'
          -d '{"text":"Job Status ${{ job.status }}"}' 
          -X POST ${{ secrets.SLACK_WEBHOOK_URL }}
